spring.application.name=clicker

spring.datasource.url=jdbc:postgresql://127.0.0.1:5432/cat_clicker
spring.datasource.username=postgres
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true